services:
    web.user_manager:
        class: Guikingone\UserBundle\Managers\Web\UserManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@session'
            - '@security.authorization_checker'
            - '@event_dispatcher'